@@include('lazy/closest.js')
@@include('lazy/blazy.min.js')


$( document ).ready(function() {
    @@include('blazy.js')
    @@include('menu.js')
    @@include('favarits.js')
    @@include('input-script.js')
    @@include('header-search.js')
    @@include('btn-settings-mobil.js')
    @@include('available-shop.js')
    @@include('stars.js')
    @@include('similar-products-slider.js')
    @@include('new-collection-slider.js')
    @@include('article-sdlider.js')
    @@include('brends-slider.js')
    @@include('first-screen-slider.js')
    @@include('good-slider.js')
    @@include('quantity.js')
    @@include('LK-payment-method.js')
    @@include('password.js')
    @@include('classie.js')
    @@include('animation-input.js')
    @@include('textarea.js')
    @@include('filter-slider-price.js')
    @@include('map.js')
})